name: Docker Build and Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t my-image:test .

      - name: Run Docker container for tests
        run: |
          docker run --rm my-image:test # 여기에 테스트 명령어 추가 가능
